### ISSUE TITLE
Simulate ObjC block syntax

### ISSUE THREAD

**Issue by IngwiePhoenix** [jayphelps/stutter.js#1]
Hey.

I just found this library and got a little curios. For my current project, I am using [OJ](https://github.com/musictheory/oj). Now I wondered how I could possibly add the Blocks syntax. Because I use OJ in [WebPack](https://github.com/webpack/webpack), I can apply a pre-processor easily.

The Blocks syntax can look like this:

``` objective-c
^(foo, bar){
    // ...
}

^(foo){
    // ...
}

^{
    // ...
}
```

The caret ("`^`") character should always be transpated to `function`, while the parantheses should always be added after the keyword. If they are missing, empty parentheses should be applied.

Is there a way to preprocess a file and turn any instance of the above into regular anonymous functions?

Kind regards, Ingwie.

**Comment by jayphelps** [comment]
Hey @IngwiePhoenix, sorry but this project is suuuper old (2012) so I don't maintain it.

But to answer your question directly, nope, this project will not let you do what you desire. That would require context-aware parsing. Take a peak at [sweetjs](http://sweetjs.org/) will might let you create a macro for this.
